name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env: 
      VITE_PROD_API_URL: https://bierdeckel.matze.fun
    steps:
      - uses: actions/checkout@v3
       # Cache npm dependencies

      # Build Quarkus and Docker
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Quarkus App (JVM)
        working-directory: ./
        run: mvn package

      # Docker Login and Push
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        working-directory: ./
        run: |
              echo "Current Directory (pwd): $(pwd)"
              docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel:latest .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel:latest
