name: Build and Deploy

on:
  push:
    branches: [ main ]  # Adjust the trigger branch as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Build React App
      - name: Install React dependencies
        working-directory: ./Frontend/Bierdeckel
        run: npm install
      - name: Build React App
        working-directory: ./Frontend/Bierdeckel
        run: npm run build

      # Copy to Quarkus
      - name: Copy React build to Quarkus resources
        if: steps.build-and-deploy.outcome == 'success' # Ensure build succeeded
        run: cp -r ./Frontend/Bierdeckel/build/* ./Backend/src/main/resources/META-INF/resources

      # Build Quarkus and Docker Image (Assuming Maven in Backend)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  
          distribution: 'temurin' 
      - name: Install GraalVM & Native Build Tools 
        # Example: Add actions to install GraalVM and any dependencies
        uses: some-action-to-setup-graalvm@v1 
      - name: Build Quarkus App (Native)
        working-directory: ./Backend
        run: mvn package -Pnative 

      # Docker Login and Push
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        working-directory: ./Backend  
        run: |   # Use a multi-line command
                  docker build -f src/main/docker/Dockerfile.native -t ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel:latest .
                  docker push ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel:latest
