name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Docker Login and Push for Frontend
      - name: Log into Docker Hub for Frontend
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image for Frontend
        working-directory: ./Frontend/Bierdeckel
        run: |
              echo "Current Directory (pwd): $(pwd)"
              docker build -f dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel-frontend:latest .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel-frontend:latest

      # Build Quarkus and Docker Image (Assuming Maven in Backend)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build Quarkus App (JVM)
        working-directory: ./Backend
        run: mvn package

      # Docker Login and Push for Backend
      - name: Log into Docker Hub for Backend
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image for Backend
        working-directory: ./Backend
        run: |
              echo "Current Directory (pwd): $(pwd)"
              docker build -dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel-backend:latest .
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/cm-bierdeckel-backend:latest
